### PR TITLE
Webfinger: don't discard consumer errors

### LINKED ISSUE #83: Error: don't drop the original error
Hi,

When trying to implement some basic activitypub functionality, I found it very hard to know where the errors came from.
For example, when implementing a basic actor and using `webfinger_resolve_actor`, I just get a `WebFingerResolveFailed` error, while my code generated more error information than that.

I suggest replacing the current `Error` value with:

```rust
pub enum ErrorKind {
    NotFound,
    RequestLimit,
    ResponseBodyLimit,
    ObjectDeleted,
    UrlVerificationError(&'static str),
    ActivityBodyDigestInvalid,
    ActivitySignatureInvalid,
    WebfingerResolveFailed,
    /// see Error::source
    Other // Here we remove the current anyhow::Error
}

pub struct Error {
    kind: Kind,
    source: Option<anyhow::Error>,
}
```

And implement the `Error` trait on top of the struct `Error`. That way using `std::Error::source` the full error information can be found.

### PR DESCRIPTION
**Pull request by sgued**
Fix #83 

Actually after looking at the code, it appears that the only time the consumer errors are actually discarded was when iterating over the links from a webfinger query. Since multiple links need to be tried there are multiple errors and it doesn't make much sense to return all of them.

Instead log the error so that it can be observed by the consumer of the library.

To resume:

This PR improves the webfinger error by:

- Making it its own enum and adding granularity
- Logging the failure when dereferencing the links from the webfinger query. This is done by adding a `Display` bound on the error type. I didn't add the full `std::error::Error` because it conflicts with some of the examples, and implementing `Error` is incompatible with `impl<T: Into<anyhow::Error>> Error for …`.
- Improving the webfinger parsing and getting rid of the regex (not fully rid of the crate since it is used in 1 more place).
The new version is equivalent to the old, tested by fuzzing.

Given that the inital issue is fixed just by adding a log line, it might make sense to drop this PR and make on that just adds the `Display` bound and the log line for simplicity.

### CODE REVIEW

File: src/fetch/webfinger.rs [hunk 1]
```diff
@@ -1,17 +1,36 @@
...
+    /// The wefinger object did not contain any link to an activitypub item
+    #[error("The wefinger object did not contain any link to an activitypub item")]
+    NoValidLink,
+}
+
+impl WebFingerError {
+    fn to_crate_error(self) -> Error {
+        self.into()
+    }
+}
```
Comment (Nutomic) [inline src/fetch/webfinger.rs:32]: Is this really necessary?

File: src/fetch/webfinger.rs [hunk 2]
```diff
@@ -89,22 +110,39 @@ where
...
+            }
+
+            if &rem[idx + 1..] != data.domain() {
+                return Err(WebFingerError::WrongDomain.into());
+            }
+
+            return Ok(&rem[..idx]);
+        } else if !accept_char_name(c) {
+            return Err(WebFingerError::WrongFormat.into());
+        }
```
Comment (Nutomic) [inline src/fetch/webfinger.rs:142]: Ah so you managed to get rid of regex to validate the webfinger query. Then you should be able to get rid of the regex dependency. Also please add some comments to explain what the code is doing.

File: src/fetch/webfinger.rs [hunk 3]
```diff
@@ -1,17 +1,36 @@
...
+#[derive(thiserror::Error, Debug)]
+pub enum WebFingerError {
+    /// The webfinger identifier is invalid
+    #[error("The webfinger identifier is invalid")]
+    WrongFormat,
+    /// The webfinger identifier doesn't match the expected instance domain name
+    #[error("The webfinger identifier doesn't match the expected instance domain name")]
+    WrongDomain,
+    /// The wefinger object did not contain any link to an activitypub item
+    #[error("The wefinger object did not contain any link to an activitypub item")]
```
Comment (Nutomic) [inline src/fetch/webfinger.rs:24]: `wefinger`

File: src/fetch/webfinger.rs (hunk 1 above)
Comment (sgued) [reply src/fetch/webfinger.rs:32]: Yes, otherwise `Err(webfinger_error.into()))?` becomes `webfinger_error.into().into()` and type inference doesn't know  what to do. This necessary when returning `Object::Error`.

The other solutions would be either to user turbofish or to use the full name of the crate error. This feels less noisy.

File: src/fetch/webfinger.rs (hunk 2 above)
Comment (sgued) [reply src/fetch/webfinger.rs:148]: I added some documentation.

The `regex` crate is also used to [parse the `Signature` header for the `keyId` of the sender](https://github.com/LemmyNet/activitypub-federation-rust/blob/main/src/http_signatures.rs#L164). I looked at actually parsing that but it seems that doing it properly would be a lot more involved. The [`sfv`](https://docs.rs/sfv) crate has in theory the correct parser but it enforces the rule from RFC 8941 that `keyId` should not be allowed to have a capital letter, which is visibly not respected by ActivityPub...

File: src/fetch/webfinger.rs (hunk 3 above)
Comment (sgued) [reply src/fetch/webfinger.rs]: Fixed in [f947f8b](https://github.com/LemmyNet/activitypub-federation-rust/pull/85/commits/f947f8b0c512cee4469087b4cd8c3d1263184b94)

File: src/fetch/webfinger.rs (hunk 2 above)
Comment (Nutomic) [reply src/fetch/webfinger.rs:148]: I see, in that case it seems much simpler to keep the regex here and capture the domain for checking `WrongDomain` error.

Comment (sgued) [reply src/fetch/webfinger.rs:148]: I have looked a bit more at the spec because I was curious to know where the `Letter` category in the regex came from (I initially only copied the behaviour of the regex).

It looks like the correct way to parse the `acct` part of a webfinger url would be to parse it as a `Url`, where `acct` is a scheme (like https), defined in https://datatracker.ietf.org/doc/html/rfc7565

It also looks like the webfinger endpoints can accept other versions of the url for an account. For example:

```
curl https://pouet.chapril.org/.well-known/webfinger?resource=acct:sgued@pouet.chapril.org
curl https://pouet.chapril.org/.well-known/webfinger?resource=https://pouet.chapril.org/users/sgued
curl https://pouet.chapril.org/.well-known/webfinger?resource=https://pouet.chapril.org/@sgued
```

All return the same value, but on the lemmy side, `curl https://lemmy.ml/.well-known/webfinger?resource=https://lemmy.ml/u/nutomic` returns an error.

This should probably be done in another PR though. I'll restore the `Regex` implementation so that this PR can be merged.

Comment (Nutomic) [reply src/fetch/webfinger.rs:148]: Yes please revert it. The current implementation is working, so Id rather keep it as is and avoid any risk of breakage. Especially when there is no practical benefit from the change.

**Comment by Nutomic** [comment]
Clippy has some complaints, otherwise looks good.
